### PR TITLE
Add support for the ESP8266.

### PR DESCRIPTION
**Pull request by nzmichaelh**
Refactor the chip and data pins to generic functions.  Add support for controlling CS and RS via the standard digitalWrite() functions.  Add support for hardware SPI only devices.

Note that I refactored the generic AVR and SAM code but unfortunately can't test it.

Performance numbers are at https://juju.net.nz/michaelh/blog/2015/05/1-8-lcd-support-for-the-esp8266/

### CODE REVIEW

**Comment by jca258** [comment]
Hi! I've got an ESP-07 and a ST7735 display. I've installed the Arduino and I'm testing with my board your library.
At the moment, I can't get the display show a single line, but I don't know if my wiring is ok. Do you know what is the ESP GPIO mapping with Arduino SDK?

**Comment by jca258** [comment]
Solved the issue!
I've got the following constant values on the graphictest example:
```
#define TFT_CS     15
#define TFT_RST    4
#define TFT_DC     2
```
And these connections:
```
GPIO15 -> CS
GPIO4  -> RST
GPIO2  -> A0
GPIO13 -> SDA
GPIO14 -> SCK
```
Thanks!

**Comment by ksteddom** [comment]
I can confirm that this fork works on the Sparkfun ESP8266 Thing, https://www.sparkfun.com/products/13231, with the AdaFruit 1.8" 160X128 TFT display breakout board, https://www.adafruit.com/product/358. The performance seems to be about the same as on an Arduino Pro Mini at 16 MHz. The pinout I used is as follows:
        Thing                TFT
           4-------------- RESET
        SDA --------------D/C
Not Connected--- CARD_CS  //I don't need the SD card for my application so I didn't mess with it
           0--------------TFT_CS
          13---------------MOSI
         SCL--------------SCK
Not Connected------MISO

The relevant portions of the graphicstest demo file are:
#define TFT_CS     0
#define TFT_RST   4
#define TFT_DC     2 
Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS,  TFT_DC, TFT_RST);                      

I also tried connecting TFT_CS to 4 and RESET to the Thing's DTR pin. This worked. The DTR pin is tied to reset on the Thing to enable upload. It also is used to switch between program code and the boot loader. I'm not sure if this will cause trouble down the road since this pin does more than just reset. Since I have extra GPIO pins for my application I will be switching back to using a specific pin for the reset.

**Comment by tsuriyathep** [comment]
I have tried it on an Adafruit Huzzah (https://www.adafruit.com/products/2821) and of course an Adafruit 1.8 TFT.  It does not work for me:

MOSI ---> MOSI
SCK ---> SCK
TFT_CS ---> 14
SD_CS ---> NONE
RST ---> 12
DC ---> 13

#define TFT_CS     14
#define TFT_RST   12
#define TFT_DC     13

**Comment by ladyada** [comment]
hiya - thank for waiting, i just tested using a feather huzzah & the latest commits, with both SPI and bitbang. DC -> 15 and CS -> 0 and reset tied to 3.3V :)

**Pull request closed without merging**
